### ISSUE TITLE
On Off Scene

### ISSUE THREAD

**Issue by BaXaras** [Joe-houghton/PushBulletDomoticz#1]
congratulations for the project, it works great I noticed that for the scenes does not work, I modified the code adding a control if I change the notification text with SOff and SOn if I have to start a scene I attach the change, congratulations again

def sendCommand(command, device):
    if command == 'SOff':
       command = 'Off'
       jsonString = '/json.htm?type=command&param=switchscene&idx='
    elif command == 'SOn':
       command = 'On'
       jsonString = '/json.htm?type=command&param=switchscene&idx='
    else:
       jsonString = '/json.htm?type=command&param=switchlight&idx='

**Comment by Joe-houghton** [comment]
Hi BaXaras,

Glad you like the project, its great to see people using it.
I have fixed this another way (I have forgotten to upload the latest code). 

I will upload the latest code tonight when I get home. I have also made it more generic, so you just add a single command to IFTTT, so it does not need to be done for every device/scene.

Joe

**Comment by Joe-houghton** [comment]
Hi BaXaras,

I have now updated the code. The command for switching a scene is #commandToScene.
But also take not of the #commandByName, which does scenes and devices. I have updated the Readme to include these.

I may update the help more later with an image to show how to set up the #commandByName on IFTTT.

Joe

**Comment by BaXaras** [comment]
perfect unique limitation that the free service can send only 100 notifications per month

**Comment by Joe-houghton** [comment]
From what I have read, it is 500 a month, but they work on a rate limit too, so if they think you are going to go over 500, they will stop it being able to work. I only came across this limit once when testing lots in my first implementation:  https://docs.pushbullet.com/#ratelimiting

**Comment by BaXaras** [comment]
good evening lately the script after a while is interrupted and I have to start again with the old version has never happened to me, in the logs I do not find anything abnormal do you have any solution?

**Comment by Joe-houghton** [comment]
I don't have this issue myself. Occasionally I have had to restart my raspberry pi (maybe twice in 8 months). The new version should not really be any different to the old version in terms of connecting and maintaining the connection.
