### ISSUE TITLE
Minor issues......

### ISSUE THREAD

**Issue by kevsterd** [Joe-houghton/PushBulletDomoticz#2]
Posted this on the Domo forum however I thought I'd add here ....

Running on a Pi3, with Raspian.

1) I had to add 'from collections import namedtuple' to stop initial runtime error

2) When I run the script I get:

> got this far
> got a pb instance

I then type the command:

> #command Off 1233

Nothing happens.....

Is there any further debugging or do I need to add to the script ?

**Comment by Joe-houghton** [comment]
Hi @kevsterd,

Thanks for your input. I think that I missed the namedtuple import when copying over to github (I do this manually so not to include my api key etc). Thanks for letting me know.

As for why it is not working - 

1. I also noticed that there was an import missing (json). I have adding this now, try with the latest code.
2. 1233 seems a very high number, are you sure that this is correct? Using the menu in the Domoticz web interface and select Setup -> Devices. Use the number that is in the Idx column.

**Comment by kevsterd** [comment]
Hi

Just re-cloned the git and its still doing the same.   Def using Python 2.7.9 as well.

The ID is correct.  I have up to ~2500 discovered devices now.

Seems very odd behavior if yours works.

**Comment by Joe-houghton** [comment]
@kevsterd,
So after the two debug messages that you mentioned, the next one should be "Data received".
If you are not getting this, then it will probably be worth checking that the command is being sent by IFTTT.
To do this, you can download a pushbullet client log on with the account that your api key is for. Now you can check that you get a notification from IFTTT.
Joe

**Comment by Joe-houghton** [comment]
@kevsterd have you had any luck yet?

**Comment by kevsterd** [comment]
Hey.  Sorry didt have chance yesterday....

Initially I thought the script running on the console was interactive !  So my bad there.   Finally setup Google Assistant, IFTTT and PushBullet.

I can see GA triggering, IFTTT then Pushbullet triggering .... however get a traceback..

Received data:
{u'subtype': u'push', u'type': u'tickle'}
ERROR:root:'result'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/listener.py", line 75, in on_message
    self.on_push(json_message)
  File "/home/pi/scripts/PushBulletDomoticz/PBDomoticz.py", line 133, in on_push
    getNewPushes()
  File "/home/pi/scripts/PushBulletDomoticz/PBDomoticz.py", line 96, in getNewPushes
    populateDevicesAndScenes()
  File "/home/pi/scripts/PushBulletDomoticz/PBDomoticz.py", line 46, in populateDevicesAndScenes
    populateUsingURL(getAllScenes, 1)
  File "/home/pi/scripts/PushBulletDomoticz/PBDomoticz.py", line 36, in populateUsingURL
    devices = jsonDevices["result"]
KeyError: 'result'

Not sure if its as it pushes to Domo or message received.

**Comment by kevsterd** [comment]
Hey.  Sorry didt have chance yesterday....

Initially I thought the script running on the console was interactive !  So my bad there.   Finally setup Google Assistant, IFTTT and PushBullet.

I can see GA triggering, IFTTT then Pushbullet triggering .... however get a traceback..

Received data:
{u'subtype': u'push', u'type': u'tickle'}
ERROR:root:'result'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/listener.py", line 75, in on_message
    self.on_push(json_message)
  File "/home/pi/scripts/PushBulletDomoticz/PBDomoticz.py", line 133, in on_push
    getNewPushes()
  File "/home/pi/scripts/PushBulletDomoticz/PBDomoticz.py", line 96, in getNewPushes
    populateDevicesAndScenes()
  File "/home/pi/scripts/PushBulletDomoticz/PBDomoticz.py", line 46, in populateDevicesAndScenes
    populateUsingURL(getAllScenes, 1)
  File "/home/pi/scripts/PushBulletDomoticz/PBDomoticz.py", line 36, in populateUsingURL
    devices = jsonDevices["result"]
KeyError: 'result'

Not sure if its as it pushes to Domo or message received.

**Comment by Joe-houghton** [comment]
Hi @kevsterd ,

So, it seems that IFTTT is now pushing correctly to the pi via PushBullet.
The error message you have posted seems to suggest that when prompting Domoticz for the list of devices available, it is not returning the correct thing, can I suggest that in a browser you use the url
http://user:pass@ipaddress:port/json.htm?type=scenes
in my case this is just
http://192.168.0.10:8080/json.htm?type=scenes
it should give you something like this:
```
{
   "ActTime" : 1527526965,
   "AllowWidgetOrdering" : true,
   "ServerTime" : "2018-05-28 17:02:45",
   "Sunrise" : "03:56",
   "Sunset" : "20:11",
   "result" : [     <--------------- Verify that this is present
      {
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2018-05-27 19:07:57",
         "Name" : "Evening", 
         "OffAction" : "",
         "OnAction" : "",
         "Protected" : false,
         "Status" : "Mixed",
         "Timers" : "false",
         "Type" : "Scene",
         "UsedByCamera" : false,
         "idx" : "1"
      },
      {
         "Description" : "",
         "Favorite" : 0,
         "LastUpdate" : "2018-05-27 21:57:00",
         "Name" : "Bedtime",
         "OffAction" : "",
         "OnAction" : "",
         "Protected" : false,
         "Status" : "Mixed",
         "Timers" : "false",
         "Type" : "Scene",
         "UsedByCamera" : false,
         "idx" : "2"
      },
```

Can you verify that you see a response that contains a list of your scenes.

If that works ok, then we will need to print out the json response in PBDomoticz.py - I can help with that if needed.

Joe

**Comment by RAIDUU** [comment]
Hey,

I had the same problem and fixed it by creating a scene in Domoticz,
Maybe this helps,

RAi

**Comment by Joe-houghton** [comment]
Thanks for that RAi, I will update the code to deal with this shortly.
Joe

**Comment by Joe-houghton** [comment]
This is now fixed. Thanks for everyone's input.
