### ISSUE TITLE
Scenes

### ISSUE THREAD

**Issue by kevsterd** [Joe-houghton/PushBulletDomoticz#3]
Hi

Thanks for explaining in the other bug thread.   I could fork and contribute I guess but still getting my head around how I do that.....

So I have an issue around the use of scenes.   If I define a scene in Domo as a type 'group'  this script seems to fail.   I suspect is due to the the API call should be different.  For me the groups work better.

If you do use scenes, in my version the scene appears to set the state of the devices (say for instance as on) and I cant see a way to define an off state

![image](https://user-images.githubusercontent.com/18176387/40998601-392f2330-6900-11e8-9242-2b96ee890c87.png)

Do others have a scene for 'all lights on' and another for 'all lights off' ?

Thanks for all your help

**Comment by Joe-houghton** [comment]
Hi @kevsterd,

I also had to research this a while back. As I understand it, a scene is meant to be a state of different devices. For example, I have a scene called "bedtime", this turns my TV off, turns my upstairs lights on etc.

I will have a look how groups work via Domoticz.

**Comment by Joe-houghton** [comment]
Looking through the API, scenes and groups should be treated the same.

When you say that group groups fail, what do you witness?

**Comment by kevsterd** [comment]
Yes - I kinda guessed that was the use for scenes as you describle, however you can configure them as groups as I mentioned which would work better for me.

Sadly I closed the ssh session I was debugging on and didnt have a log saved.   I will next time.

Ill have to test tomorrow now as turning on/off will wake the house !

**Comment by Joe-houghton** [comment]
Hi @kevsterd,

I have set up a group and tested this, it seems to be working.
If you are still having problems can you get errors from the log or any other information to help figure the issue out.

Joe

**Comment by kevsterd** [comment]
Sorry this has taken a while.  

So I think PB is working.  More of an issue at the Domo end and I managed to get it to push the task to domo this morning

```
Received data:
{u'subtype': u'push', u'type': u'tickle'}
All Lights On
#commandToScene On 1
(u'http://10.10.10.10:8080/json.htm?type=command&param=switchscene&idx=1&switchcmd=On', '\n')
Received data:
{u'subtype': u'push', u'type': u'tickle'}
Received data:
{u'subtype': u'push', u'type': u'tickle'}
Received data:
{u'subtype': u'push', u'type': u'tickle'}
All Lights Off
#commandToScene Off 1
(u'http://10.10.10.10:8080/json.htm?type=command&param=switchscene&idx=1&switchcmd=Off', '\n')
Received data:
{u'subtype': u'push', u'type': u'tickle'}
Received data:
{u'subtype': u'push', u'type': u'tickle'}
```
I also tested the switch and that works perfectly.   My issue appears to be with Domo as the group does nothing with the Off action it seems, so I need to investigate there..

**Comment by kevsterd** [comment]
Just changed it to a group in Domo and its all working.   Thanks for your help
