### ISSUE TITLE
How to send a command

### ISSUE THREAD

**Issue by maartenaalbers** [Joe-houghton/PushBulletDomoticz#4]
Hi,
I am totally new to Pushbullet, but how do I send a command?
I installed everything on my Pi, added the key and Domoticz config, but how can I test a command?
Maarten.

**Comment by Joe-houghton** [comment]
Hi Maarten,

You need to set up IFTTT to send a pushbullet notification. You can then trigger your IFTTT applet from Google assistant or Alexa, or anything else that will trigger an applet. The command structure is noted in the readme
