### ISSUE TITLE
What do I put here?

### ISSUE THREAD

**Issue by keithcrooks1** [Joe-houghton/PushBulletDomoticz#6]
Right I copied and pasted my API key as below (Characters xxx'd out for security)
What do I put in Host and Port I left as none it wasnt happy and tried the IP and Port of the computer the software runs but it still wasny happy
 
API_KEY = 'o.VUxxxpNxx3xxxxxxxxf1xCmxxxZxE'
#HTTP_PROXY_HOST = 192.168.2.xxx
#HTTP_PROXY_PORT = xxxx

Cheers

**Comment by Joe-houghton** [comment]
Hi,
Do you use a proxy server to access the internet? If not, then leave HTTP_PROXY_HOST alone.

You want to put the IP of your Domoticz device here:
DOMOTICZ_ADDRESS = 'http://192.168.0.1:8080'

**Comment by keithcrooks1** [comment]
thankyou
