### ISSUE TITLE
Not receiving pushes

### ISSUE THREAD

**Issue by BillyTheGit** [Joe-houghton/PushBulletDomoticz#7]
I installed it on a Rasp Pi 3 and everything seems to work.. except that I'm not receiving any pushes.
The pushes (send from IFTTT with Google Assistant) are received on other devices, but nothing changes in Domoticz.

I'm seeing this, do pushes also need to appear here?

> pi@raspberrypi:~ $ python3 /home/pi/scripts/PushBulletDomoticz/PBDomoticz.py
> 
> Initialising
> 
> PB instance Created
> 
> Listening for pushes

Thank you in advance.

**Comment by Joe-houghton** [comment]
Not sure I follow 100% to where you are currently at, but I presume you are running
_python3 /home/pi/scripts/PushBulletDomoticz/PBDomoticz.py__
and you are seeing the output 
_Initialising PB instance Created
Listening for pushes_

You also say that you are receiving pushes on other devices. Are you closing the connection from the other devices, so that they are not taking the pushes before the raspberry pi.

**Comment by BillyTheGit** [comment]
Thank you for the quick reply.
Yes indeed, that is what Im running and what I am seeing.

What do yo mean by closing the connection? Would a new Pushbullet account make a difference?
I closed the push notification after a couple of minutes, since I guessed it should work faster than that.

**Comment by Joe-houghton** [comment]
So if you have a mobile or desktop/web app for pushbullet then make sure that it is closed, else it will take the push and the pi will not receive it.

**Comment by h0ppie** [comment]
@Joe-houghton Am I understanding this correctly? Let's say I'm in the following situation: I'm sitting in my office working on my laptop in Chrome with the Pushbullet extension installed, I tell Google Home to turn on the light in my living room. Then there might be a chance that my laptop (or actually the extension) will catch the push before the Pi does?

I don't want to be harsh or anything, just trying understand it and after that maybe help in finding a solution. 😁

**Comment by Joe-houghton** [comment]
Hi,
Sorry for the delay, I've been at work.
The line in the ReadMe
sudo pip install pushbullet.py
Installs the pushbullet library, via pip 
I believe that is what will happen, easy way to get round this is to just use another account for pushbullet that is artiste from the one you use for other things. Plus you probably wouldn't want to receive lots of "turn on xxx" notifications on your browser.
Joe
