### ISSUE TITLE
Missing link to pushbullet.py

### ISSUE THREAD

**Issue by h0ppie** [Joe-houghton/PushBulletDomoticz#8]
Hi @Joe-houghton,

I was looking through the code and saw the function `get_pushes()`, which looked familiar since I'm a bt familiar with `pushbullet.py` plugin. What do you think about adding the link to that plugin as well in the ReadMe? So people can look into the code of that plugin as well. Just a brainfart from my side :)

It was this one right, which you have to install? https://github.com/rbrcsk/pushbullet.py

**Comment by Joe-houghton** [comment]
It is installed via pip as it makes for a more simple install from this repository's perspective.
I have added a link anyway.
